Meghana urerfbranchfix test
neurodata/SPORF pull request #308
Opened 2019-08-01 16:16 UTC by falkben

This continues the work to fix urerf in PR #306

@megh1241 made the fix and I added a python class and pytest to ensure it is working.

I decided to make a new class, and copied most of the code, instead of adding new functionality to the existing rerf class/module.  This could be considered bad design -- let me know what you think.  Initially thought that we'd be using a very different design for doing urerf, but now that it's done, I think we could shoehorn it into our existing rerf class, just overwriting defaults when necessary.

Also updated docs to include urerf and added a demo notebook.

2019-08-01 19:21 UTC, MrAE requested changes
Cool. A few minor comments

2019-08-01 19:21 UTC, MrAE commented on Python/rerf/urerf.py
> +    min_samples_split : int, optional (default: 1)
I thought we had determined default of 1 resulted in poor performance.
However, its current default is "auto"

2019-08-01 19:21 UTC, MrAE commented on packedForest/src/forestTypes/unsupervisedForests/baseUnprocessedNodeUnsupervised.h
> +				baseUnprocessedNodeUnsupervised(int numObsForRoot):  parentID(0), depth(0), isLeftNode(true){
trailing whitespace.

2019-08-01 19:21 UTC, MrAE commented on packedForest/src/forestTypes/unsupervisedForests/urerf/fpURerFBase.h
>  				return 0;
If not used, should this return -1?

2019-08-01 19:21 UTC, MrAE commented on packedForest/src/forestTypes/unsupervisedForests/urf/fpURFBase.h
>  				return 0;
If not used, should this return -1?

2019-08-01 19:25 UTC, MrAE commented
I'm fine with it being its own class. If it lasts long enough, we can shoehorn it in later if absolutely necessary.

2019-08-01 19:29 UTC, falkben commented on packedForest/src/forestTypes/unsupervisedForests/urerf/fpURerFBase.h
>  				return 0;
@megh1241

2019-08-06 15:02 UTC, MrAE approved these changes

2019-08-07 17:30 UTC, merged